########## Config Map: Environment Settings ##########
apiVersion: v1
kind: ConfigMap
metadata:
  name: myrabbitmq-configmap
data:
  env_rabbitmq_host: "myrabbitmq"
  env_rabbitmq_port: "5672"
  env_rabbitmq_username: Z3Vlc3Q=
  env_rabbitmq_password: Z3Vlc3Q=
---
########## Deployment: Producer ##########
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproducer
  labels:
    app: myproducer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproducer
  template:
    metadata:
      labels:
        app: myproducer
    spec:
      containers:
      - name: myproducer
        image: yaowl/messaging-producer-api:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        - containerPort: 5001
        env:
        - name: ENV_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_host
        - name: ENV_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_port
        - name: ENV_RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_username
        - name: ENV_RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: myrabbitmq-configmap
              key: env_rabbitmq_password
---
########## Service: Producer ##########
apiVersion: v1
kind: Service
metadata:
  name: myproducer-service
spec:
  type: NodePort
  selector:
    app: myproducer
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31500
    name: "producernossl"
  - port: 5001
    targetPort: 5001
    nodePort: 31501
    name: "producerssl"
---
########## HorizontalPodAutoscaler: Autoscaling for Producer ##########
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: myproducer-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myproducer
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75